// Automatically generated by jlox.tool.GenerateAst

package jlox;
import java.util.List;

@SuppressWarnings("unused")
abstract class Stmt {
  interface VoidVisitor {
    void visitBlockStmt(Block stmt);
    void visitContinueCatcherStmt(ContinueCatcher stmt);
    void visitExpressionStmt(Expression stmt);
    void visitFunctionStmt(Function stmt);
    void visitIfStmt(If stmt);
    void visitKeywordStmt(Keyword stmt);
    void visitLastStmt(Last stmt);
    void visitPrintStmt(Print stmt);
    void visitReturnStmt(Return stmt);
    void visitVarStmt(Var stmt);
    void visitWhileStmt(While stmt);
  }
  interface Visitor<R> {
    R visitBlockStmt(Block stmt);
    R visitContinueCatcherStmt(ContinueCatcher stmt);
    R visitExpressionStmt(Expression stmt);
    R visitFunctionStmt(Function stmt);
    R visitIfStmt(If stmt);
    R visitKeywordStmt(Keyword stmt);
    R visitLastStmt(Last stmt);
    R visitPrintStmt(Print stmt);
    R visitReturnStmt(Return stmt);
    R visitVarStmt(Var stmt);
    R visitWhileStmt(While stmt);
  }

  static class Block extends Stmt {
    final List<Stmt> statements;

    Block ( List<Stmt> statements ) {
      this.statements = statements;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitBlockStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitBlockStmt(this);
    }
  }

  static class ContinueCatcher extends Stmt {
    final Stmt statement;

    ContinueCatcher ( Stmt statement ) {
      this.statement = statement;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitContinueCatcherStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitContinueCatcherStmt(this);
    }
  }

  static class Expression extends Stmt {
    final Expr expression;

    Expression ( Expr expression ) {
      this.expression = expression;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitExpressionStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitExpressionStmt(this);
    }
  }

  static class Function extends Stmt {
    final Token name;
    final List<Token> parameters;
    final List<Stmt> body;

    Function ( Token name, List<Token> parameters, List<Stmt> body ) {
      this.name = name;
      this.parameters = parameters;
      this.body = body;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitFunctionStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitFunctionStmt(this);
    }
  }

  static class If extends Stmt {
    final Expr condition;
    final Stmt then;
    final Stmt else_;

    If ( Expr condition, Stmt then, Stmt else_ ) {
      this.condition = condition;
      this.then = then;
      this.else_ = else_;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitIfStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitIfStmt(this);
    }
  }

  static class Keyword extends Stmt {
    final Token keyword;

    Keyword ( Token keyword ) {
      this.keyword = keyword;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitKeywordStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitKeywordStmt(this);
    }
  }

  static class Last extends Stmt {
    final Expr expression;

    Last ( Expr expression ) {
      this.expression = expression;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitLastStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitLastStmt(this);
    }
  }

  static class Print extends Stmt {
    final Expr expression;

    Print ( Expr expression ) {
      this.expression = expression;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitPrintStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitPrintStmt(this);
    }
  }

  static class Return extends Stmt {
    final Token keyword;
    final Expr value;

    Return ( Token keyword, Expr value ) {
      this.keyword = keyword;
      this.value = value;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitReturnStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitReturnStmt(this);
    }
  }

  static class Var extends Stmt {
    final Token name;
    final Expr initializer;

    Var ( Token name, Expr initializer ) {
      this.name = name;
      this.initializer = initializer;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitVarStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitVarStmt(this);
    }
  }

  static class While extends Stmt {
    final Expr condition;
    final Stmt body;

    While ( Expr condition, Stmt body ) {
      this.condition = condition;
      this.body = body;
    }

    @Override
    void voidVisit(VoidVisitor visitor) {
        visitor.visitWhileStmt(this);
    }

    @Override
    <R> R visit(Visitor<R> visitor) {
        return visitor.visitWhileStmt(this);
    }
  }

    abstract void voidVisit(VoidVisitor visitor);

    @SuppressWarnings("UnusedReturnValue")
    abstract <R> R visit(Visitor<R> visitor);
}
